version: "3.8"

services:
  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - "./services/backend:/app"
      - "/app/node_modules"
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    network_mode: host

  frontend:
    build: ./services/frontend
    volumes:
      - "./services/frontend:/app"
    ports:
      - 8080:8080

  nginx:
    image: nginx:alpine
    volumes:
      - ./services/frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
